---
name: "AppImage"
permissions:
  contents: write
on:
  pull_request:
  push:
jobs:
  AppImage:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Install nix
        uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: remove full tex to reduce size
        run: sed -i '2i \  plugins.vimtex.texlivePackage=null;' config/vimtex.nix
      - name: Create the appImage
        run: nix bundle --bundler github:ralismark/nix-appimage .
      - name: "Upload appImage"
        uses: softprops/action-gh-release@v1
        with:
          files: nixvim-x86_64.AppImage
          tag_name: nixvim
